### ISSUE TITLE
Reactivate GitReleaseManagerAddAssets

### ISSUE THREAD

**Issue by Meerownymous** [icarus-consulting/Yaapii.Http#99]
### Expected Behavior
Cake script uploads assets to Github

### Actual Behavior
Currently, due to unknown reasons, GitReleaseManager fails with this exception:

```
Uploading assets
[FTL] Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at GitReleaseManager.Core.VcsService.<AddAssetsAsync>d__13.MoveNext() in /_/src/GitReleaseManager.Core/Vcs
Service.cs:line 147
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitReleaseManager.Core.Commands.AddAssetsCommand.<Execute>d__3.MoveNext() in /_/src/GitReleaseManager.Core/Commands/AddAssetsCommand.cs:line 21
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitReleaseManager.Cli.Program.<Main>d__1.MoveNext() in /_/src/GitReleaseManager.Cli/Program.cs:line 34
An error occurred when executing task '
GitHubRelease
'.

```

### Mention any other details that might be useful
Adding of assets has been deactivated in cake script to allow releasing package. It must be reactivated and repaired (or maybe there is currently a bug which might be solved by the authors, so that reactivating is enough).

**Comment by DFU398** [comment]
no longer relevant since we no longer use git release manager, see #123
